### ISSUE TITLE
GitHub push rejected

### ISSUE THREAD

**Issue by caliendojulien** [timkrase/phpunit-coverage-badge#17]
I got a error with GitHub push when I try to update the badge.

`
 ! [remote rejected] HEAD -> refs/pull/[6](https://github.com/****/bando/actions/runs/4231050905/jobs/7349093212#step:16:6)2/merge (shallow update not allowed)
error: failed to push some refs to 'https://github.com/****/bando.git'
`

**Comment by timkrase** [comment]
Were you able to find out what the problem was? I'd assume it has to do with the way the code is checked out in the action. Is the repository public and you can link it so I can have a look?
