### ISSUE TITLE
Getting a "Could not open input file: src/entry.php" error

### ISSUE THREAD

**Issue by PhrozenByte** [timkrase/phpunit-coverage-badge#4]
Unfortunately I can't get `phpunit-coverage-badge` working, running the action always results in a

> Could not open input file: src/entry.php

error. I'm a GitHub Actions beginner, so maybe I just do it wrong.

Here's my workflow config: https://github.com/PhrozenByte/phpunit-throwable-asserts/blob/master/.github/workflows/coverage.yml
And here's a failing run: https://github.com/PhrozenByte/phpunit-throwable-asserts/runs/1757698367#step:7:12

**Comment by timkrase** [comment]
Thanks for reporting. Your configuration looks good to me. I'll have a look at it.

**Comment by timkrase** [comment]
Thanks for submitting your repository together with the error message. Was very helpful for debugging the problems. 

Seems like the action only worked for me because I ran it in its own repository. I fixed some of the problems but still try to figure out why pushing the badge is not working outside of my repository. I hope to release a new stable version in the upcoming days.

**Comment by PhrozenByte** [comment]
From your description I'd assume that it might be about different working directories? Like if you run it on a different project the current working directory isn't `phpunit-coverage-badge`, but the other project? I don't know :see_no_evil: Just digging in the dark. Thanks for investigating! :+1:

**Comment by timkrase** [comment]
> From your description I'd assume that it might be about different working directories? Like if you run it on a different project the current working directory isn't `phpunit-coverage-badge`, but the other project? I don't know 🙈 Just digging in the dark. Thanks for investigating! 👍

Yep, you've been completely right. For some reason every command has been executed in the runner's workspace, even when I changed directories before executing the command. I had to cd into the github workspace before every command execution to make it work. I'll clean my debugging code up, build the image again and release a new (working) version soon. I'll let you know then.

**Comment by timkrase** [comment]
I've just released v1.2.0 and it worked on my fork of your project. Let me know if it now works as expected for you. I'll gladly accept further suggestions on how to improve the action or maybe even PR if you want to get your hands dirty.

**Comment by PhrozenByte** [comment]
Works like a charm ([[1]](https://github.com/PhrozenByte/phpunit-throwable-asserts/commit/6942e36f77611866b4f2659ae206e4159cd13ed2) [[2]](https://github.com/PhrozenByte/phpunit-throwable-asserts/runs/1780541880#step:7:1)) :rocket: :+1: 

Great work, thank you! :smiley: 

*Off Topic:* If Git doesn't work so well for some reason (I'm no Docker user either, so no idea :see_no_evil:), you might simply drop this feature. I was thinking about pushing a HTML coverage report to a just-a-copy-of-README.md GitHub Pages website and saw that there's even a GitHub Action specifically for committing files, https://github.com/marketplace/actions/add-commit. This is the first time I actually use GitHub Actions (I was a Travis and Scrutinizer user), but damn, GitHub made CI so easy with all those great actions - like yours! :muscle:
