### ISSUE TITLE
GHA not working in project

### ISSUE THREAD

**Issue by adpe** [timkrase/phpunit-coverage-badge#8]
Hi @timkrase 

I've tried to implement this action with the Moodle GHA workflow. But it always gives this failure https://github.com/adpe/moodle-local_pluginsfetcher/runs/2149406206?check_suite_focus=true#step:19:1.

Can you help out?

Thanks
Adrian

**Comment by timkrase** [comment]
Hi @adpe. Thanks for reporting. 

Unluckily pushing the badge does not seem to work if the github checkout action is not using the default path. Maybe only generating the badge and pushing it using another (more sophisticated) pushing action might work. I've forked your repo and will give it a try.

**Comment by timkrase** [comment]
Have a look here: https://github.com/timkrase/moodle-local_pluginsfetcher/tree/feature/remove-coveralls-report

This does at least work, but I feel like it will be random which of the different runs will produce the badge (or depend on their speed rather than randomness). I'll have a closer look at your project at the weekend and think about how such cases can be dealt with.

**Comment by adpe** [comment]
Thank you very much @timkrase to find out a working solution.

Will check if I'll migrate from Coveralls.io to this `local` solution. As I see, I don't get the expected result of code coverage, but I'll give it again a try.

What would be a better name for this issue? We can rename it.

What do you mena by using "default path", as I add `.coverage/badge.svg`? I'll check it out with `badge.svg` in the root directory.

Greets
Adrian

**Comment by adpe** [comment]
Quick update @timkrase

As I see, it works with other then default paths, check out https://github.com/adpe/moodle-local_pluginsfetcher/tree/feature/remove-coveralls-report. Furthermore, with an `if-statement` you can control in which job you want to create and commit the badge. So we've a solution for the different runs.

Thanks for your help!
Adrian
