### ISSUE TITLE
Add text support as ReportParser

### ISSUE THREAD

**Issue by adpe** [timkrase/phpunit-coverage-badge#9]
Hi @timkrase 

Why does this action not supports the `coverage-text` output?

Greets
Adrian

**Comment by timkrase** [comment]
Thanks for pointing that out, didn't knew that existed to be honest. Not sure I'll find the time right now to implement that so if you (or someone else who stumbles upon this) want to give it a try feel free to do so and submit a PR.

**Comment by adpe** [comment]
Hi @timkrase 

This feature is unnecessary as the `coverage-text` option will always generate a `clover.xml` file. Therefore, I'll close this issue.

Thanks anyway and greets
Adrian
